### ISSUE TITLE
No such table: translation_mimasamodel

### ISSUE THREAD

**Issue by adrimat007** [developers-cosmos/Mimasa#57]
When i try to translete, demo audio or something , i get the error , thats because  translation_mimasamodel dont exist or cant be reacheable.

## Steps to Reproduce

1. Start all service 
2. Press register for translation

## Error:

sqlite3.OperationalError: no such table: translation_mimasamodel

The above exception was the direct cause of the following exception:

Mimasa\venv\Lib\site-packages\django\db\backends\utils.py", line 90, in _execute
    return self.cursor.execute(sql, params)

## Additional Information

- Operating System: Windows
- Browser: Chrome

**Comment by RitheeshBaradwaj** [comment]
@adrimat007 Hi, thanks for reporting your issue. The Django server reports the error mentioned because the Django models are missing. Can you run the below commands?

```bash
python src/api/mimasa/manage.py makemigrations
python src/api/mimasa/manage.py migrate
```

**Comment by adrimat007** [comment]
@RitheeshBaradwaj hello i do it on installation but i do another time 

First run print:
`<django.db.backends.utils.CursorDebugWrapper object at 0x0000028D5E4B2F50>
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name None
<django.db.backends.utils.CursorDebugWrapper object at 0x0000028D5E50EBD0> SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" ()
No changes detected
`
Second run: 
`<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C3B6D90> 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name None
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C3E11D0> SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" ()
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C3E3FD0>
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name None
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C3F4AD0> SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" ()
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C42B050>
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name None
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C42B290>
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name None
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C430150> SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" ()
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C3F7D50> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('admin',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C444550> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('admin', 'logentry')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C375410> SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."conte
nt_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (%s) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC (1,)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C445610> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('admin',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C4464D0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('auth',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C446B90> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('auth', 'permission')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C4471D0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('auth', 'group')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C447950> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('auth', 'user')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C447C90> SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."conte
nt_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (%s, %s, %s) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC (2, 3, 4)       
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C432D90> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('auth',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C447950> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('contenttypes',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C448310> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('contenttypes', 'contenttype')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C446F50> SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."conte
nt_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (%s) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC (5,)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C447790> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('contenttypes',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C446DD0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('sessions',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C448C90> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('sessions', 'session')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C448D90> SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."conte
nt_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (%s) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC (6,)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C447C10> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('sessions',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C446C10> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('translation',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C4491D0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."
app_label" = %s AND "django_content_type"."model" = %s) LIMIT 21 ('translation', 'mimasamodel')
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C4334D0> SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."conte
nt_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (%s) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC (7,)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C432BD0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('translation',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C449490> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('audio_separation',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C448BD0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('audio_separation',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C448BD0> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('face_detection',)
<django.db.backends.utils.CursorDebugWrapper object at 0x000002489C449A10> SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."a
pp_label" = %s ('face_detection',)
`
i get the same error:
The above exception (no such table: translation_mimasamodel) was the direct cause of the following exception:

**Comment by RitheeshBaradwaj** [comment]
@adrimat007 Have you created your database locally? Usually, you have to create your database and define your settings in [settings.py for Django](https://docs.djangoproject.com/en/4.2/topics/settings/) on your own. For reference, I added my `settings.py` script. Could you please create your database and keep it in the `src/api/mimasa` directory?
